### ISSUE TITLE
OOM with visualize script

### ISSUE THREAD

**Issue by hadfield** [DeepGraphLearning/GNN-QE#2]
I get an OOM error with the visualize script:

RuntimeError: CUDA out of memory. Tried to allocate 22.00 MiB (GPU 0; 22.20 GiB total capacity; 19.53 GiB already allocated; 4.06 MiB free; 20.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

Running via:
` python script/visualize.py -c config/fb15k237_visualize.yaml --checkpoint ~/scratch/experiments/LogicalQuery/FB15k237LogicalQuery/GNN-QE/2022-09-18-13-34-00/model_epoch_10.pth`

I was able to run training ok after adjusting the batch_size in the config.

Any advice on adjusting config for the visualize script to avoid the OOM error?  I'm testing this in an AWS environment with 24G GPUs.

**Comment by hadfield** [comment]
(I'll just run this on a machine with bigger GPUs, but am curious if anything can be tweaked in the config.)

**Comment by hadfield** [comment]
FYI, this does work fine for me when i switched to a bigger GPU on google cloud.

**Comment by KiddoZhu** [comment]
Hi! The GPU memory consumption is generally proportional to the batch size. The default configuration file is tuned according to a 32GB GPU, but you may change it to fit into smaller GPUs.

**Comment by hadfield** [comment]
Yes, I get OOM with batch size of 1 for the visualize script whereas the train script works in the same environment. (and they both work fine with larger GPUs).
