### ISSUE TITLE
ninja issue

### ISSUE THREAD

**Issue by chandeler** [DeepGraphLearning/GNN-QE#5]
hi, thanks for the excellent work.
but i really met some problem on reproducing the code

the error is:
```
Command ‘[‘ninja‘, ‘-v‘]‘ returned non-zero exit status 1
LINK : fatal error LNK1104: cannot open“python37.lib” 
ninja: build stopped: subcommand failed.
```

it has puzzled me for several days, i see in the NBFnet issues, other people also met the ninja issue on a linux machine. 

In my situation, I am on a windows10 rtx3080 machine. with torchdrug fixed to 0.1.13 i have tried different  version of python, torch, but met the same ninja problem.

wishing for some advice to help me out*-*

**Comment by KiddoZhu** [comment]
Hi! I haven't met this problem before. It looks like ninja can't link the python library. Could you try to manually add the python libraries to the environment variable? For example, Windows (PowerShell) may use something like `$env:LIB += ";C:\Program Files\Python37\libs"`. You may also checkout the [installation guide here](https://torchdrug.ai/docs/installation.html#windows-powershell).

**Comment by chandeler** [comment]
thanks for the reply~, i have solved the problem through reinsatlling cuda10.1.&nbsp; Maybe torchdrug is not compatible with cuda11.1 or 3090.&nbsp;



---Original---
From: "Zhaocheng ***@***.***&gt;
Date: Sun, Nov 6, 2022 04:44 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [DeepGraphLearning/GNN-QE] ninja issue (Issue #5)




 
Hi! I haven't met this problem before. It looks like ninja can't link the python library. Could you try to manually add the python libraries to the environment variable? For example, Windows (PowerShell) may use something like $env:LIB += ";C:\Program Files\Python37\libs". You may also checkout the installation guide here.
